
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class authorise extends javax.swing.JFrame {

    /**
     * Creates new form authorise
     */
    public authorise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Password");

        p1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("AUTHORISE YOUR PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p1)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}  
int sn=0;
    private void txn() {
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            Statement stmt = con.createStatement();
            String query = "select txn from statement;";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
               sn = rs.getInt("txn");
            }

            sn = sn + 1;

            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }    
    }

String b="";
private void bal()
{
try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            Statement stmt=con.createStatement();

                String q="select * from balance where accno="+home.user.getText()+";";
                ResultSet rs=stmt.executeQuery(q);
                while(rs.next())
                {
                 b=rs.getString("available");              
                                
                }
                rs.close();
                stmt.close();
                con.close();
        }

        catch (Exception e) {
            System.out.print(e);
        }
}    
String use="";
String name1="";    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
txn();
String free="NULL";
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
Calendar cal = Calendar.getInstance();
String date = formatter.format(cal.getTime());
String pwd = new String (p1.getPassword()) ;
String pwd1="";
String name1="";
Double bal1 = null;
Double bal2 = null;
try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","");
            Statement stmt=con.createStatement();
            String query="select username,password,accno from users where accno="+transfer.myac.getText()+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                pwd1=rs.getString("password");
                name1=rs.getString("username");             
            }

            if(pwd.equals(pwd1))
            {
                String query1="select * from balance where accno="+transfer.myac.getText()+";";
                ResultSet rs1=stmt.executeQuery(query1);
                while(rs1.next())
                {
                  bal1=rs1.getDouble("available");
                }
                bal1=bal1 - Double.parseDouble(transfer.amt.getText());
                String b1=Double.toString(bal1);
                String query2="select * from balance where accno="+transfer.to.getText()+";";
                ResultSet rs2=stmt.executeQuery(query2);
                while(rs2.next())
                {
                  bal2=rs2.getDouble("available");           
                }
                bal2=bal2 + Double.parseDouble(transfer.amt.getText());
                String b2=Double.toString(bal2);
                String q="update balance set available=available - "+ transfer.amt.getText() +" where accno=" + transfer.myac.getText() +";";
                String q1="update balance set available=available + "+ transfer.amt.getText() +" where accno=" + transfer.to.getText() +";";
                String q2="insert into statement values("+Integer.toString(sn)+", "+ transfer.myac.getText() +", " + transfer.to.getText()
                          +", "+ transfer.amt.getText() +",'"+date+"','"+ transfer.remark.getSelectedItem()+"');";
                String q3="insert into a"+transfer.myac.getText()+" values("+Integer.toString(sn)+",'"+date+"','"+transfer.remark.getSelectedItem()+"',"+
                       free+"," +transfer.amt.getText()+","+b1+");";
                String q4="insert into a"+transfer.to.getText()+" values("+Integer.toString(sn)+",'"+date+"','"+transfer.remark.getSelectedItem()+"',"
                        +transfer.amt.getText()+","+free+","+b2+");";
                stmt.execute(q);
                stmt.execute(q1);
                stmt.execute(q2);
                stmt.execute(q3);
                stmt.execute(q4);
                                
                JOptionPane.showMessageDialog(this, "Money Transfer Succesfull.");
                close();
                home n=new home();
                n.setVisible(true);
                home.user.setText(use);
                home.name.setText(name1);  
                bal();
                home.balance.setText("Rs "+b);        
                
            }

            else
            {
                JOptionPane.showMessageDialog(this,"Transaction Declined Due To Invalid Password.");
                close();
                login n=new login();
                n.setVisible(true);
            }

            rs.close();
            stmt.close();
            con.close();
        }

        catch (Exception e) {
            System.out.print(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
use=home.user.getText();
name1=home.name.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated


       
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(authorise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(authorise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(authorise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(authorise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new authorise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField p1;
    // End of variables declaration//GEN-END:variables
}
