
import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class newac extends javax.swing.JFrame {

    /**
     * Creates new form newac
     */
    public newac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lnam = new javax.swing.JTextField();
        gen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        add1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add2 = new javax.swing.JTextField();
        stat = new javax.swing.JTextField();
        cit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        occupation = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        pin = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(580, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        fnam.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        fnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnamKeyTyped(evt);
            }
        });
        getContentPane().add(fnam);
        fnam.setBounds(230, 80, 146, 40);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 134, 40);

        lnam.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnamKeyTyped(evt);
            }
        });
        getContentPane().add(lnam);
        lnam.setBounds(230, 130, 146, 40);

        gen.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(gen);
        gen.setBounds(460, 80, 60, 40);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 134, 40);

        t3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(230, 180, 146, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 230, 134, 40);

        p1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(p1);
        p1.setBounds(230, 230, 146, 40);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 280, 146, 40);

        p2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2);
        p2.setBounds(230, 280, 146, 40);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 380, 134, 40);

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel13.setText("YYYY-MM-DD");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 380, 116, 40);

        add1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(add1);
        add1.setBounds(230, 430, 155, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("Address Line 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 430, 134, 40);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("Address Line 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 484, 134, 40);

        add2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(add2);
        add2.setBounds(230, 480, 155, 40);

        stat.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        stat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                statKeyTyped(evt);
            }
        });
        getContentPane().add(stat);
        stat.setBounds(230, 530, 155, 40);

        cit.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                citKeyTyped(evt);
            }
        });
        getContentPane().add(cit);
        cit.setBounds(230, 580, 155, 40);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 680, 155, 40);

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setText("Phone");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 680, 134, 40);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setText("Pincode");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 627, 134, 40);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setText("City");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 580, 134, 40);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setText("State");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 530, 134, 40);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("Occupation");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 330, 134, 40);

        occupation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        occupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Job", "Business", "Student" }));
        getContentPane().add(occupation);
        occupation.setBounds(230, 330, 160, 40);

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setText("First Name");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 80, 134, 40);
        getContentPane().add(date1);
        date1.setBounds(230, 380, 160, 40);

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setText("Log In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 580, 81, 40);

        pin.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });
        getContentPane().add(pin);
        pin.setBounds(230, 630, 155, 40);

        phone.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(230, 680, 155, 40);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setText("Register New Account");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 10, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int accno = 0;
    private void number() {
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            Statement stmt = con.createStatement();
            String query = "select accno from users;";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
               accno = rs.getInt("accno");
            }

            accno = accno + 1;

            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }

    }

private void close()
{
    WindowEvent winClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
}      

    Calendar rightNow = Calendar.getInstance();
    int y = rightNow.get(Calendar.YEAR);
    int m = rightNow.get(Calendar.MONTH) + 1;
    int d = rightNow.get(Calendar.DAY_OF_MONTH);

    String y1 = Integer.toString(y);
    String m1 = Integer.toString(m);
    String d1 = Integer.toString(d);
    String max = y1 + "-" + m1 + "-" + d1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        number();
        String gender = (String) gen.getSelectedItem();
        String occu=(String) occupation.getSelectedItem();
        String fname = fnam.getText();
        String lname = lnam.getText();
        String user = t3.getText();
        String pwd = new String(p1.getPassword());
        String cpwd = new String(p2.getPassword());
        String address1 = add1.getText();
        String address2 = add2.getText();
        String state = stat.getText();
        String city = cit.getText();
        String pincode = pin.getText();
        int pincode2=Integer.parseInt(pin.getText());
        String phon = phone.getText();
        long phone2=Long.parseLong(phone.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String dob = formatter.format(date1.getDate());
        

        int lpwd = pwd.length();
        int lcpwd = cpwd.length();
        int lpin = pincode.length();
        int lphon = phon.length();
        int ladd1 = address1.length();
        int fname1 = fname.length();
        int lname1 = lname.length();
        int lstate = state.length();
        int lcity = city.length();
        int luser = user.length();
        int x=0;
        int z=luser-1;
        for(int y=0;y<=z;y++)
        {
            char c=user.charAt(y);
            String h=c+"";
            if(" ".equals(h))
            {
                x=x+1;
            }
        }
        String n = "";
        String preuser = "";
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
            Statement stmt = con.createStatement();
            String query = "select username,accno from users where username='" + user + "';";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next())
            {
                preuser = rs.getString("username");
            }
            String accno1 = Integer.toString(accno);
            if (user.equals(preuser))
            {
                JOptionPane.showMessageDialog(this, "Username Not Available.");
            }
            if (x>=1 || luser==0)
            {
                JOptionPane.showMessageDialog(this, "Invalid Username");
            }
            else
            {
                if(pincode2>=100000 && phone2>=1000000000 && lpwd >= 8 && lcpwd >= 8
                    && pwd.equals(cpwd) && fname1 != 0 && lname1 != 0 && ladd1 != 0
                    && lstate != 0 && lcity != 0 && luser != 0 && occupation.getSelectedIndex()!=0)
                {
                    String q = "insert into users values(" + accno1 + ",'" + user + "','" + pwd + "','" 
                                + fname + "','" + lname + "','" + address1 + "','" + address2 + "','" + state + "','"
                                + city + "','" + pincode + "','" + phon + "','" + dob +"','"+ gender+"','"+ occupation.getSelectedItem() +"');";
                    stmt.execute(q);
                    String record="create table a"+accno1+"(txn int primary key not null, date date, remarks varchar(100) not null, "
                            + "credit double precision, debit double precision, balance double precision not null);";
                    stmt.execute(record);
                    String bal = "insert into balance values(" + accno1 + ",0);";
                    stmt.execute(bal);
                    JOptionPane.showMessageDialog(this, "Registered Successfully");
                    
                    
                }
                else
                {
                    String error="Please Check";
                    if (fname1 == 0)
                    {
                        error+="\n"+"First Name";
                    }
                    if (lname1 == 0)
                    {
                        error+="\n"+"Last Name";
                    }
                    if (luser == 0)
                    {
                        error+="\n"+"User Name";
                    }
                    if (!pwd.equals(cpwd))
                    {
                        error+="\n"+"Password Do Not Match";
                    }
                    if (lpwd < 8)
                    {
                        error+="\n"+"Password";
                    }
                    if (lcpwd < 8)
                    {
                        error+="\n"+"Confirm Password";
                    }
                    if (occupation.getSelectedIndex()==0)
                    {
                        error+="\n"+"Select Occupation";
                    }
                    if (ladd1 == 0)
                    {
                        error+="\n"+"Address";
                    }
                    if (lstate == 0)
                    {
                        error+="\n"+"State";
                    }
                    if (lcity == 0)
                    {
                        error+="\n"+"City";
                    }
                    if (pincode2<100000)
                    {
                        error+="\n"+"Pincode";
                    }
                    if (phone2<1000000000)
                    {
                        error+="\n"+"Phone No.";
                    }
                    JOptionPane.showMessageDialog(this, error);
                }
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch (Exception e)
        {
            System.out.print(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Calendar cal = Calendar.getInstance();
        java.util.Date t=cal.getTime();   
        
date1.setMaxSelectableDate(t);
date1.setDate(t);
Font f=fnam.getFont();
date1.setFont(f);
pin.setFont(f);
phone.setFont(f);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
login n=new login();
n.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnamKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_fnamKeyTyped

    private void lnamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnamKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_lnamKeyTyped

    private void statKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_statKeyTyped

    private void citKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();           // TODO add your handling code here:
    }//GEN-LAST:event_citKeyTyped

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isDigit(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();
    if(pin.getText().length()==6)
        evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_pinKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
char c=evt.getKeyChar();

    if(!(Character.isDigit(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume(); 
    if(phone.getText().length()==10)
        evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_phoneKeyTyped

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
char c=evt.getKeyChar();

    if(!(Character.isLetterOrDigit(c) ||  (c==KeyEvent.VK_BACKSPACE)||  c==KeyEvent.VK_DELETE ))
        evt.consume();         // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1;
    private javax.swing.JTextField add2;
    private javax.swing.JTextField cit;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField fnam;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lnam;
    private javax.swing.JComboBox<String> occupation;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField stat;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
